---
http_interactions:
- request:
    method: put
    uri: https://us.apiconnect.ibmcloud.com/v1/portal/orgs/SAMPLE_ORG_ID/apps/SAMPLE_APP_ID
    body:
      encoding: UTF-8
      string: '{"name":"Demo","appImageURL":"https://something.com/empty.jpg","description":"pro
        demo app","oauthRedirectURI":"https://advanced.demo.cl","public":true}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - us.apiconnect.ibmcloud.com
      Authorization:
      - Basic U0FNUExFX1VTRVJOQU1FOlNBTVBMRV9QQVNTV09SRA==
      X-Ibm-Apimanagement-Context:
      - bci-api-developers-sandbox-desarrollo.local-registry
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 21 Nov 2017 19:04:03 GMT
      Server:
      - Apache
      Strict-Transport-Security:
      - max-age=15768000
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Pragma:
      - No-cache
      Cache-Control:
      - no-cache
      Expires:
      - Thu, 01 Jan 1970 00:00:00 UTC
      Content-Location:
      - https://us.apiconnect.ibmcloud.com/v1/portal/orgs/SAMPLE_ORG_ID/apps/SAMPLE_APP_ID
      Content-Type:
      - application/json
      Vary:
      - Accept-Encoding
      X-Xss-Protection:
      - '1'
      X-Content-Type-Options:
      - nosniff
      X-Apim:
      - 169.55.21.17
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"type":"PRODUCTION","promoteTo":null,"id":"SAMPLE_APP_ID","name":"Demo","orgID":"SAMPLE_ORG_ID","public":true,"description":"pro
        demo app","credentials":{"clientID":"f08f8a08-7bb8-4172-9f0e-8ab824d2d6f1","clientSecret":"********************************************","description":"Default","url":"https://us.apiconnect.ibmcloud.com/v1/portal/orgs/SAMPLE_ORG_ID/apps/SAMPLE_APP_ID/credentials"},"appCredentials":[{"id":"5a1432b60cf2cc3097526007","description":"Default","url":"https://us.apiconnect.ibmcloud.com/v1/portal/orgs/SAMPLE_ORG_ID/apps/SAMPLE_APP_ID/credentials/5a1432b60cf2cc3097526007","clientID":"f08f8a08-7bb8-4172-9f0e-8ab824d2d6f1","clientSecret":"********************************************"}],"enabled":true,"state":"ACTIVE","imageURL":null,"appImageURL":"https://something.com/empty.jpg","oauthRedirectURI":"https://advanced.demo.cl","certificate":null,"createdAt":"2017-11-21T14:05:42.982+0000","updatedAt":"2017-11-21T14:05:42.982+0000","url":"https://us.apiconnect.ibmcloud.com/v1/portal/orgs/SAMPLE_ORG_ID/apps/SAMPLE_APP_ID"}'
    http_version: 
  recorded_at: Tue, 21 Nov 2017 19:04:03 GMT
recorded_with: VCR 3.0.3
